from typing import Literal
from pydantic import BaseModel

class Plan(BaseModel):
    """
    execute the plan generated by the supervisor
    """
    steps:list[
        Literal[
            "rag",
            "web",
            "maintenance",
        ]
    ]
    reason:str